version: '2'
services:
    apache:
        build: .docker/apache
        container_name: apache_sf
        ports:
          - 8042:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: mysql_sf
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf
            MYSQL_USER: sf
            MYSQL_PASSWORD: sf

    php:
        build: .docker/php
        container_name: php_sf
        volumes:
          - .:/home/wwwroot/sf
        environment:
          - maildev_host=maildev_sf
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_sf
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: maildev_sf
        ports:
          - 8001:80
